name: Check modified files

on:
  pull_request:
    branches:
    - main 

jobs:
  check-files:
    runs-on: ubuntu-latest 
    steps:
      - name: Get
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'

      - name: Check Files
        run: |
          readarray -t changed_file <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.all }}')"
          for changed_file in ${changed_file[@]}; do
            echo "Removed files: ${changed_file}." >> check_file_report.log
          done
      
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: check_file_report.log