name: Check remote host and push report

on:
  push:
    branches:
    - main 

jobs:
  prepare:
    runs-on: ubuntu-latest 
    steps:
    
      - name: Check Files
        id: files
        uses: jitterbit/get-changed-files@v1

        run: |
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          for added_modified_file in "${added_modified_files[@]}"; do
            echo "Do something with this ${added_modified_file}."
          done
        
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: nc_report.log