name: Check remote host and push report

on:
  push:
    branches:
    - main 

jobs:
  prepare:
    runs-on: ubuntu-latest 
    steps:
    
      - name: Check Files
        id: files
        uses: jitterbit/get-changed-files@v1
#        with:
#          format: 'json'

      - run: |
          readarray -t removed_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.removed }}')"
          for removed_file in ${removed_files[@]}; do
            echo "Do something with this ${removed_file}." > nc_report.log 2>&1
          done
        
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: nc_report.log