name: Check remote host and push report

on:
  push:
    branches:
    - main 

jobs:
  prepare:
    runs-on: ubuntu-latest 
    steps:
    
      - name: Check Files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'

      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "This file has been changed ${changed_file}." > nc_report.log 2>&1
          done
        
      - name: Upload report 
        uses: actions/upload-artifact@v2
        with:
          path: nc_report.log