name: Check remote host and push report

on:
  push:
    branches:
    - main 

jobs:
  prepare:
    runs-on: ubuntu-latest 
    steps:
      - name: Install netcat 
        run: sudo apt update && sudo apt install -y netcat
      - run: echo "netcat has been installed"
      - run: |
          nc -z -v -w2 onliner.by 443 > nc_report.log 2>&1
          ls -la
    
      - name: Check Files
      -  id: files
      -  uses: jitterbit/get-changed-files@v1

      - name: Output
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}." > nc_report.log 2>&1
          done
        
      - name: Upload report 
        uses: actions/upload-artifact@v2
        with:
          path: nc_report.log